### ISSUE TITLE
Feature Request: Keyboard to controller mapping (ColecoVision/MSX, etc)

### ISSUE THREAD

**Issue by KMFDManic** [libretro/FBAlphaFB#4]
BlueMSX has truly excellent keyboard to controller mapping, that was implemented awhile back, on my request...thanks to fr500.  ColecoVision/MSX games have the caveat of Coleco (keypad on the controller with numbers, etc) and MSX (many keybinds for games like Metal Gear 1/2 requiring F1/F2/F3/F4, N, A, Space Bar, etc.

This isn't a super high priority request.  But, it would be very nice to have more optimal support to handle the nuanced control schemes for these systems, specifically.

Thanks so much, as always, for all the incredible work that you have all put forth in FBA!

I would have opened this request on the "newer fork" of FBA.  But, it does not seem as if issues can be opened there, as of yet.

**Comment by KMFDManic** [comment]
@barbudreadmon Thank you for the response.  I will do more testing today.  But, my initial testing was with several Coleco Games that loaded fine.  But, they get to the selection screen for difficulty levels, and could not be bypassed.  I went into controls, and saw the controls were mapped as up down left right and fire 1 fire 2.  These generally worked fine for BlueMSX  But, I found Cabbage Patch Kids Adventures in the Park (cabbage.zip) would not start.  Some games, like Gyruss, do not have selection menus, so start absolutely fine with the fire button.

I am also very appreciative of the Adam Computer Coleco Super Games that were added.  I really need to test those.  

Again, thanks!  I will do more testing the moment I can.  

P.S.: On BlueMSX, most games bypass menu selection with fire button, with exception of Turbo, from my testing.

**Comment by barbudreadmon** [comment]
> I went into controls, and saw the controls were mapped as up down left right and fire 1 fire 2

Every button is available for me, though the default mapping isn't nice : 
![screenshot](https://user-images.githubusercontent.com/10391265/57389833-4c091f00-71bb-11e9-883c-677c5283be13.png)

Are you sure you aren't using an old version of the core ?

**Comment by KMFDManic** [comment]
@barbudreadmon I will try the latest commits and confirm whether controls are there or not.  That mapping looks a lot better than in my test with just the 2 fire buttons:)  Nice to see what appears to be the SGM version of Buck Rogers!  How well do the SGM games run, anyways?  I am particularly interested in Dragon's Lair and Buck Rogers, two of my mainstays from when I had an ADAM computer way back!  I wanted a Commodore 64!  But, I ended up getting an ADAM instead.

**Comment by barbudreadmon** [comment]
> How well do the SGM games run, anyways?

I think they run well but i might be wrong since i never played them on the real hardware.

**Comment by barbudreadmon** [comment]
Can i close ?

**Comment by KMFDManic** [comment]
@barbudreadmon will close it to keep things tidy on your end.  Thanks for your input and I will respond if I have any issues.  I still did not get to test due to work.  But, I should be able to today.  Thanks!

**Comment by KMFDManic** [comment]
@barbudreadmon Ok, I found the cause of them not mapping.  It was just a goof in the compile, which lead to a segfaul, and it is now sorted.  I do have one other question, however.  I would love some enlightenment on the running of the SGM Games, since they are essentially publicly available with their Special ReRelease.  I have the base Coleco/MSX, etc games running fine.  Anything special I would need to do for the SGM games to have them properly load up?  Not sure exactly what is expected inside the .zip files that you have set as:

cv_buckrogsgm, cv_dlairsgm, etc.  I am particularly interested in the SGM ones, as myself and another recently got these going on MESS 2016.  But, I am really loving how you guys added support for these to FBA!

Thanks again for your feedback:)
